apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tm-app-prod-backend-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: backend-prod-tamacoach-aws-secretsmanager
  target:
    name: tm-app-prod-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: host
    - secretKey: dbname
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: dbname
    - secretKey: username
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: username
    - secretKey: password
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: password
    - secretKey: port
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: port
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tm-app-prod-worker-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: backend-prod-tamacoach-aws-secretsmanager
  target:
    name: tm-app-prod-worker-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: host
    - secretKey: dbname
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: dbname
    - secretKey: username
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: username
    - secretKey: password
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: password
    - secretKey: port
      remoteRef:
        key: tamacoach-prod/backend/prod/secrets
        property: port