apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tm-app-prod-backend
  namespace: apps
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:193629269600:targetgroup/tamacoach-shared-backend-prod-tg/6f7c7bb0c3c81ba5
  targetType: ip
  serviceRef:
    name: tm-app-prod-backend
    port: 8000