apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tm-app-dev-backend
  namespace: apps
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:193629269600:targetgroup/tamacoach-shared-backend-dev-tg/b1d14e8c8a8f6886
  targetType: ip
  serviceRef:
    name: tm-app-dev-backend
    port: 8000