fullnameOverride: ""

image:
  repository: ""
  digest: ""

workloads:
  backend:
    enabled: true
    replicaCount: 1
    command: []
    args: []
    envFrom:
      secretName: ""
  worker:
    enabled: true
    replicaCount: 1
    command: []
    args: []
    envFrom:
      secretName: ""
